// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

// ✅ Mobile-friendly: expose tiny diagnostics without console
declare global {
  interface Window {
    __DORA_SUPABASE__?: { url: string | null; hasAnonKey: boolean };
  }
}

if (typeof window !== "undefined") {
  window.__DORA_SUPABASE__ = {
    url: SUPABASE_URL ?? null,
    hasAnonKey: Boolean(SUPABASE_ANON_KEY),
  };
}

// ✅ Hard fail early if env missing (prevents silent “nothing shows” bugs)
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    "Missing Supabase env. Check VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Lovable secrets."
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});