// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = import.meta.env.VITE_DORA_SUPABASE_URL as string | undefined;
const SUPABASE_ANON_KEY = import.meta.env.VITE_DORA_SUPABASE_ANON_KEY as string | undefined;

// ✅ Hard fail early if env missing (prevents silent “nothing shows” bugs)
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    `Missing Supabase env variables:
VITE_DORA_SUPABASE_URL set? ${Boolean(SUPABASE_URL)}
VITE_DORA_SUPABASE_ANON_KEY set? ${Boolean(SUPABASE_ANON_KEY)}`,
  );
}

// NOTE:
// Keep the client untyped until we can regenerate full schema types.
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
